// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"
)

type Dictionary struct {
	ID         int32
	Word       string
	Origin     sql.NullString
	Fullword   sql.NullString
	Definition sql.NullString
	Etymology  sql.NullString
	Type       sql.NullString
	Sentence   sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
