// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: word.sql

package database

import (
	"context"
	"database/sql"
)

const createWord = `-- name: CreateWord :one
INSERT INTO dictionary (word, origin, fullWord, definition, etymology, type, sentence) 
VALUES ($1, $2, $3, $4, $5, $6, $7) 
RETURNING id, word, origin, fullword, definition, etymology, type, sentence, created_at, updated_at
`

type CreateWordParams struct {
	Word       string
	Origin     sql.NullString
	Fullword   sql.NullString
	Definition sql.NullString
	Etymology  sql.NullString
	Type       sql.NullString
	Sentence   sql.NullString
}

func (q *Queries) CreateWord(ctx context.Context, arg CreateWordParams) (Dictionary, error) {
	row := q.db.QueryRowContext(ctx, createWord,
		arg.Word,
		arg.Origin,
		arg.Fullword,
		arg.Definition,
		arg.Etymology,
		arg.Type,
		arg.Sentence,
	)
	var i Dictionary
	err := row.Scan(
		&i.ID,
		&i.Word,
		&i.Origin,
		&i.Fullword,
		&i.Definition,
		&i.Etymology,
		&i.Type,
		&i.Sentence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
